Profile page and Leaderboard (along with search feature)
CMPUT301W23T32/lordofthewings pull request #102
Opened 2023-03-19 09:27 UTC by mansooranis

2023-03-19 23:09 UTC, KrishLal requested changes

2023-03-19 23:09 UTC, KrishLal commented on code/local.properties
> +sdk.dir=/Users/mansoor/Library/Android/sdk
Please delete your local sdk location before pushing to develop
Other than this everything looks good!  👍 
Great work!!

2023-03-20 02:07 UTC, KrishLal commented on code/local.properties
> +sdk.dir=/Users/mansoor/Library/Android/sdk
will delete the sdk in a commit afterwards.

2023-03-20 02:07 UTC, KrishLal approved these changes

2023-03-20 17:54 UTC, manan3172003 approved these changes

2023-03-20 19:16 UTC, merged

2023-04-03 10:18 UTC, mkhan1107 commented
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=US+07.01.01&pane=issue&itemId=19914129
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=US+05.01.01&pane=issue&itemId=19914108